/**
 * Asset name <-> hash resolution, backed by asset_save_keys.json (bundled static
 * data, generated by PartInfoLogger's DumpCampaignProgress). Ported from
 * SaveEditor/lpw_tool.py's AssetKeyMap.
 *
 * The asset hash is FNV1a32(SaveKey), where SaveKey is a separate per-asset
 * string that does NOT always equal the asset's .name -- never recompute hashes
 * from names locally, always resolve through this static table.
 */
import * as fs from "node:fs";

interface AssetKeyMapEntry {
  hash: number;
  type: string;
}

export class AssetKeyMap {
  private readonly hashToName: ReadonlyMap<number, string>;
  private readonly nameToHash: ReadonlyMap<string, number>;

  private constructor(hashToName: Map<number, string>, nameToHash: Map<string, number>) {
    this.hashToName = hashToName;
    this.nameToHash = nameToHash;
  }

  static load(path: string): AssetKeyMap {
    const raw = fs.readFileSync(path, "utf8");
    const keymap: Record<string, AssetKeyMapEntry> = JSON.parse(raw);
    const hashToName = new Map<number, string>();
    const nameToHash = new Map<string, number>();
    for (const [name, info] of Object.entries(keymap)) {
      hashToName.set(info.hash, name);
      nameToHash.set(name, info.hash);
    }
    return new AssetKeyMap(hashToName, nameToHash);
  }

  resolve(hash: number): string {
    return this.hashToName.get(hash) ?? `<unknown:${hash}>`;
  }

  hashOf(name: string): number {
    const hash = this.nameToHash.get(name);
    if (hash === undefined) {
      throw new Error(
        `'${name}' not found in asset_save_keys.json. Re-run PartInfoLogger's ` +
          "DumpCampaignProgress in-game to refresh it (the game must have this asset loaded at the time).",
      );
    }
    return hash;
  }
}
